apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot_stream_analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot_stream_analysis
  template:
    metadata:
      labels:
        app: iot_stream_analysis
    spec:
      containers:
      - name: iot_stream_analysis
        image: airflow/iot_stream_analysis:latest
        ports:
        - containerPort: 5000  # Assuming it uses port 5000, update if different
        env:
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: SPARK_MASTER
          value: spark://spark-master:7077
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres