apiVersion: v1
kind: Service
metadata:
  name: iot_stream_analysis
spec:
  type: ClusterIP
  ports:
  - port: 5000  # Assuming the application listens on port 5000
    targetPort: 5000
  selector:
    app: iot_stream_analysis