apiVersion: v1
kind: Service
metadata:
  name: iot-data-streaming
spec:
  type: ClusterIP
  ports:
  - port: 5000  # Assuming the application listens on port 5000
    targetPort: 5000
  selector:
    app: iot-data-streaming