apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: airflow/spark-master
        ports:
        - containerPort: 7077
        - containerPort: 8080
        - containerPort: 4040
        env:
        - name: INIT_DAEMON_STEP
          value: setup_spark