apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: ClusterIP
  ports:
  - port: 7077
    targetPort: 7077
  - port: 8080
    targetPort: 8080
  - port: 4040
    targetPort: 4040
  selector:
    app: spark-master