apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: airflow/spark-worker
        ports:
        - containerPort: 8081
        env:
        - name: SPARK_MASTER
          value: spark://spark-master:7077